name: Package

on:
  workflow_dispatch: # Allow running the workflow manually from the GitHub UI
  push:
    branches:
      - 'master'
    paths:
      - 'SharedKernel.nuspec'
  pull_request:
    branches:
      - '*' # Run the workflow for all pull requests

jobs:
  package-build-publish:
    name: Build the source

    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependency
        run: dotnet restore SharedKernel.sln

      - name: Build application
        run: dotnet build --configuration Release SharedKernel.sln

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: '6.x'

      - name: Create the package
        run: nuget pack SharedKernel.nuspec -NoDefaultExcludes

      - name: Publish the package
        run: nuget push *.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_KEY}} -SkipDuplicate
